//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcDay2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.Reviews = new HashSet<Reviews>();
            this.Stock = new HashSet<Stock>();
        }
    
        public int Id { get; set; }
        
        //[Required(ErrorMessage ="you must enter the name")]
        //[MinLength(3,ErrorMessage ="enter more than 3 letters")]
        //[MaxLength(20,ErrorMessage ="cant be more than 20letters")]
       // [RegularExpression(pattern:"[a-z]{3,20}",ErrorMessage="")]
        public string Name { get; set; }

        //[Range(minimum: 100, maximum: 10000)]
        public Nullable<double> Price { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReviewsCounter { get; set; }
        public string Color { get; set; }
        public Nullable<double> Size { get; set; }
        public Nullable<double> Discout { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string image { get; set; }
        
        //[Required]
        //[Range(minimum:1,maximum:1000)]
        //[Display(Name="Product Quantity")]
        public int Quantity { get; set; }
    
        public virtual CategoriesType CategoriesType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviews> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
