//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcDay2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smartphones
    {
        public int ProductId { get; set; }
        public Nullable<int> SmartphonesBrand { get; set; }
    
        public virtual SmartphonesBrands SmartphonesBrands { get; set; }
    }
}
