// <auto-generated />
namespace WebApi_Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class nnnnf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nnnnf));
        
        string IMigrationMetadata.Id
        {
            get { return "202103241628522_nnnnf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
