//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace day1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LapTopBrands
    {
        public int LapTopBrandId { get; set; }
        public string LapTopBrandname { get; set; }
    
        public virtual LapTop LapTop { get; set; }
    }
}
